// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Tools.proto
// Protobuf Java Version: 4.30.0

package com.st.cloud.gametool.proto;

public final class ToolsProto {
  private ToolsProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      ToolsProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 积分
     * </pre>
     *
     * <code>int64 score = 1;</code>
     * @return The score.
     */
    long getScore();

    /**
     * <pre>
     * 单注
     * </pre>
     *
     * <code>int64 bet = 2;</code>
     * @return The bet.
     */
    long getBet();
  }
  /**
   * Protobuf type {@code ClientReq}
   */
  public static final class ClientReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientReq)
      ClientReqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        ClientReq.class.getName());
    }
    // Use ClientReq.newBuilder() to construct.
    private ClientReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClientReq() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ToolsProto.internal_static_ClientReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ToolsProto.internal_static_ClientReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientReq.class, Builder.class);
    }

    public static final int SCORE_FIELD_NUMBER = 1;
    private long score_ = 0L;
    /**
     * <pre>
     * 积分
     * </pre>
     *
     * <code>int64 score = 1;</code>
     * @return The score.
     */
    @Override
    public long getScore() {
      return score_;
    }

    public static final int BET_FIELD_NUMBER = 2;
    private long bet_ = 0L;
    /**
     * <pre>
     * 单注
     * </pre>
     *
     * <code>int64 bet = 2;</code>
     * @return The bet.
     */
    @Override
    public long getBet() {
      return bet_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (score_ != 0L) {
        output.writeInt64(1, score_);
      }
      if (bet_ != 0L) {
        output.writeInt64(2, bet_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (score_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, score_);
      }
      if (bet_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, bet_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientReq)) {
        return super.equals(obj);
      }
      ClientReq other = (ClientReq) obj;

      if (getScore()
          != other.getScore()) return false;
      if (getBet()
          != other.getBet()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getScore());
      hash = (37 * hash) + BET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBet());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ClientReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ClientReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ClientReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ClientReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientReq)
        ClientReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ToolsProto.internal_static_ClientReq_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ToolsProto.internal_static_ClientReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientReq.class, Builder.class);
      }

      // Construct using com.st.cloud.game.newCommand.protobuf.ToolsProto.ClientReq.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        score_ = 0L;
        bet_ = 0L;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ToolsProto.internal_static_ClientReq_descriptor;
      }

      @Override
      public ClientReq getDefaultInstanceForType() {
        return ClientReq.getDefaultInstance();
      }

      @Override
      public ClientReq build() {
        ClientReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ClientReq buildPartial() {
        ClientReq result = new ClientReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ClientReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.score_ = score_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bet_ = bet_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientReq) {
          return mergeFrom((ClientReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientReq other) {
        if (other == ClientReq.getDefaultInstance()) return this;
        if (other.getScore() != 0L) {
          setScore(other.getScore());
        }
        if (other.getBet() != 0L) {
          setBet(other.getBet());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                score_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                bet_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long score_ ;
      /**
       * <pre>
       * 积分
       * </pre>
       *
       * <code>int64 score = 1;</code>
       * @return The score.
       */
      @Override
      public long getScore() {
        return score_;
      }
      /**
       * <pre>
       * 积分
       * </pre>
       *
       * <code>int64 score = 1;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(long value) {

        score_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 积分
       * </pre>
       *
       * <code>int64 score = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0L;
        onChanged();
        return this;
      }

      private long bet_ ;
      /**
       * <pre>
       * 单注
       * </pre>
       *
       * <code>int64 bet = 2;</code>
       * @return The bet.
       */
      @Override
      public long getBet() {
        return bet_;
      }
      /**
       * <pre>
       * 单注
       * </pre>
       *
       * <code>int64 bet = 2;</code>
       * @param value The bet to set.
       * @return This builder for chaining.
       */
      public Builder setBet(long value) {

        bet_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 单注
       * </pre>
       *
       * <code>int64 bet = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBet() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bet_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientReq)
    }

    // @@protoc_insertion_point(class_scope:ClientReq)
    private static final ClientReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientReq();
    }

    public static ClientReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientReq>
        PARSER = new com.google.protobuf.AbstractParser<ClientReq>() {
      @Override
      public ClientReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClientReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientReq> getParserForType() {
      return PARSER;
    }

    @Override
    public ClientReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 赢金额
     * </pre>
     *
     * <code>int64 win = 1;</code>
     * @return The win.
     */
    long getWin();

    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 2;</code>
     * @return The rtp.
     */
    String getRtp();
    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 2;</code>
     * @return The bytes for rtp.
     */
    com.google.protobuf.ByteString
        getRtpBytes();

    /**
     * <pre>
     * 是否免费
     * </pre>
     *
     * <code>bool isFree = 3;</code>
     * @return The isFree.
     */
    boolean getIsFree();
  }
  /**
   * Protobuf type {@code ClientRes}
   */
  public static final class ClientRes extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientRes)
      ClientResOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        ClientRes.class.getName());
    }
    // Use ClientRes.newBuilder() to construct.
    private ClientRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClientRes() {
      rtp_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ToolsProto.internal_static_ClientRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ToolsProto.internal_static_ClientRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientRes.class, Builder.class);
    }

    public static final int WIN_FIELD_NUMBER = 1;
    private long win_ = 0L;
    /**
     * <pre>
     * 赢金额
     * </pre>
     *
     * <code>int64 win = 1;</code>
     * @return The win.
     */
    @Override
    public long getWin() {
      return win_;
    }

    public static final int RTP_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object rtp_ = "";
    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 2;</code>
     * @return The rtp.
     */
    @Override
    public String getRtp() {
      Object ref = rtp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rtp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 2;</code>
     * @return The bytes for rtp.
     */
    @Override
    public com.google.protobuf.ByteString
        getRtpBytes() {
      Object ref = rtp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rtp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISFREE_FIELD_NUMBER = 3;
    private boolean isFree_ = false;
    /**
     * <pre>
     * 是否免费
     * </pre>
     *
     * <code>bool isFree = 3;</code>
     * @return The isFree.
     */
    @Override
    public boolean getIsFree() {
      return isFree_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (win_ != 0L) {
        output.writeInt64(1, win_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rtp_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, rtp_);
      }
      if (isFree_ != false) {
        output.writeBool(3, isFree_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (win_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, win_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rtp_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, rtp_);
      }
      if (isFree_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isFree_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientRes)) {
        return super.equals(obj);
      }
      ClientRes other = (ClientRes) obj;

      if (getWin()
          != other.getWin()) return false;
      if (!getRtp()
          .equals(other.getRtp())) return false;
      if (getIsFree()
          != other.getIsFree()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWin());
      hash = (37 * hash) + RTP_FIELD_NUMBER;
      hash = (53 * hash) + getRtp().hashCode();
      hash = (37 * hash) + ISFREE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFree());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ClientRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ClientRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ClientRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ClientRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientRes)
        ClientResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ToolsProto.internal_static_ClientRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ToolsProto.internal_static_ClientRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientRes.class, Builder.class);
      }

      // Construct using com.st.cloud.game.newCommand.protobuf.ToolsProto.ClientRes.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        win_ = 0L;
        rtp_ = "";
        isFree_ = false;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ToolsProto.internal_static_ClientRes_descriptor;
      }

      @Override
      public ClientRes getDefaultInstanceForType() {
        return ClientRes.getDefaultInstance();
      }

      @Override
      public ClientRes build() {
        ClientRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ClientRes buildPartial() {
        ClientRes result = new ClientRes(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ClientRes result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.win_ = win_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rtp_ = rtp_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isFree_ = isFree_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientRes) {
          return mergeFrom((ClientRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientRes other) {
        if (other == ClientRes.getDefaultInstance()) return this;
        if (other.getWin() != 0L) {
          setWin(other.getWin());
        }
        if (!other.getRtp().isEmpty()) {
          rtp_ = other.rtp_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getIsFree() != false) {
          setIsFree(other.getIsFree());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                win_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                rtp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                isFree_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long win_ ;
      /**
       * <pre>
       * 赢金额
       * </pre>
       *
       * <code>int64 win = 1;</code>
       * @return The win.
       */
      @Override
      public long getWin() {
        return win_;
      }
      /**
       * <pre>
       * 赢金额
       * </pre>
       *
       * <code>int64 win = 1;</code>
       * @param value The win to set.
       * @return This builder for chaining.
       */
      public Builder setWin(long value) {

        win_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 赢金额
       * </pre>
       *
       * <code>int64 win = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        win_ = 0L;
        onChanged();
        return this;
      }

      private Object rtp_ = "";
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @return The rtp.
       */
      public String getRtp() {
        Object ref = rtp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rtp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @return The bytes for rtp.
       */
      public com.google.protobuf.ByteString
          getRtpBytes() {
        Object ref = rtp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rtp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @param value The rtp to set.
       * @return This builder for chaining.
       */
      public Builder setRtp(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        rtp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtp() {
        rtp_ = getDefaultInstance().getRtp();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @param value The bytes for rtp to set.
       * @return This builder for chaining.
       */
      public Builder setRtpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rtp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean isFree_ ;
      /**
       * <pre>
       * 是否免费
       * </pre>
       *
       * <code>bool isFree = 3;</code>
       * @return The isFree.
       */
      @Override
      public boolean getIsFree() {
        return isFree_;
      }
      /**
       * <pre>
       * 是否免费
       * </pre>
       *
       * <code>bool isFree = 3;</code>
       * @param value The isFree to set.
       * @return This builder for chaining.
       */
      public Builder setIsFree(boolean value) {

        isFree_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否免费
       * </pre>
       *
       * <code>bool isFree = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFree() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isFree_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientRes)
    }

    // @@protoc_insertion_point(class_scope:ClientRes)
    private static final ClientRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientRes();
    }

    public static ClientRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientRes>
        PARSER = new com.google.protobuf.AbstractParser<ClientRes>() {
      @Override
      public ClientRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClientRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientRes> getParserForType() {
      return PARSER;
    }

    @Override
    public ClientRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Tools.proto\"\'\n\tClientReq\022\r\n\005score\030\001 \001(" +
      "\003\022\013\n\003bet\030\002 \001(\003\"5\n\tClientRes\022\013\n\003win\030\001 \001(\003" +
      "\022\013\n\003rtp\030\002 \001(\t\022\016\n\006isFree\030\003 \001(\010B3\n%com.st." +
      "cloud.game.newCommand.protobufB\nToolsPro" +
      "tob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ClientReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientReq_descriptor,
        new String[] { "Score", "Bet", });
    internal_static_ClientRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientRes_descriptor,
        new String[] { "Win", "Rtp", "IsFree", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
