// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Tools.proto
// Protobuf Java Version: 4.30.0

package com.st.cloud.gametool.proto;

public final class ToolsProto {
  private ToolsProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      ToolsProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 积分
     * </pre>
     *
     * <code>int64 score = 1;</code>
     * @return The score.
     */
    long getScore();

    /**
     * <pre>
     * 单注
     * </pre>
     *
     * <code>int64 bet = 2;</code>
     * @return The bet.
     */
    long getBet();

    /**
     * <pre>
     * 是否购买模式
     * </pre>
     *
     * <code>bool pay = 3;</code>
     * @return The pay.
     */
    boolean getPay();

    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 4;</code>
     * @return The rtp.
     */
    java.lang.String getRtp();
    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 4;</code>
     * @return The bytes for rtp.
     */
    com.google.protobuf.ByteString
        getRtpBytes();

    /**
     * <pre>
     * 使用血池
     * </pre>
     *
     * <code>bool useBloodPool = 8;</code>
     * @return The useBloodPool.
     */
    boolean getUseBloodPool();
  }
  /**
   * Protobuf type {@code ClientReq}
   */
  public static final class ClientReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientReq)
      ClientReqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        ClientReq.class.getName());
    }
    // Use ClientReq.newBuilder() to construct.
    private ClientReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClientReq() {
      rtp_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.st.cloud.gametool.proto.ToolsProto.ClientReq.class, com.st.cloud.gametool.proto.ToolsProto.ClientReq.Builder.class);
    }

    public static final int SCORE_FIELD_NUMBER = 1;
    private long score_ = 0L;
    /**
     * <pre>
     * 积分
     * </pre>
     *
     * <code>int64 score = 1;</code>
     * @return The score.
     */
    @java.lang.Override
    public long getScore() {
      return score_;
    }

    public static final int BET_FIELD_NUMBER = 2;
    private long bet_ = 0L;
    /**
     * <pre>
     * 单注
     * </pre>
     *
     * <code>int64 bet = 2;</code>
     * @return The bet.
     */
    @java.lang.Override
    public long getBet() {
      return bet_;
    }

    public static final int PAY_FIELD_NUMBER = 3;
    private boolean pay_ = false;
    /**
     * <pre>
     * 是否购买模式
     * </pre>
     *
     * <code>bool pay = 3;</code>
     * @return The pay.
     */
    @java.lang.Override
    public boolean getPay() {
      return pay_;
    }

    public static final int RTP_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rtp_ = "";
    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 4;</code>
     * @return The rtp.
     */
    @java.lang.Override
    public java.lang.String getRtp() {
      java.lang.Object ref = rtp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 4;</code>
     * @return The bytes for rtp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRtpBytes() {
      java.lang.Object ref = rtp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USEBLOODPOOL_FIELD_NUMBER = 8;
    private boolean useBloodPool_ = false;
    /**
     * <pre>
     * 使用血池
     * </pre>
     *
     * <code>bool useBloodPool = 8;</code>
     * @return The useBloodPool.
     */
    @java.lang.Override
    public boolean getUseBloodPool() {
      return useBloodPool_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (score_ != 0L) {
        output.writeInt64(1, score_);
      }
      if (bet_ != 0L) {
        output.writeInt64(2, bet_);
      }
      if (pay_ != false) {
        output.writeBool(3, pay_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rtp_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, rtp_);
      }
      if (useBloodPool_ != false) {
        output.writeBool(8, useBloodPool_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (score_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, score_);
      }
      if (bet_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, bet_);
      }
      if (pay_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, pay_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rtp_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, rtp_);
      }
      if (useBloodPool_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, useBloodPool_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.st.cloud.gametool.proto.ToolsProto.ClientReq)) {
        return super.equals(obj);
      }
      com.st.cloud.gametool.proto.ToolsProto.ClientReq other = (com.st.cloud.gametool.proto.ToolsProto.ClientReq) obj;

      if (getScore()
          != other.getScore()) return false;
      if (getBet()
          != other.getBet()) return false;
      if (getPay()
          != other.getPay()) return false;
      if (!getRtp()
          .equals(other.getRtp())) return false;
      if (getUseBloodPool()
          != other.getUseBloodPool()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getScore());
      hash = (37 * hash) + BET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBet());
      hash = (37 * hash) + PAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPay());
      hash = (37 * hash) + RTP_FIELD_NUMBER;
      hash = (53 * hash) + getRtp().hashCode();
      hash = (37 * hash) + USEBLOODPOOL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUseBloodPool());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.st.cloud.gametool.proto.ToolsProto.ClientReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientReq)
        com.st.cloud.gametool.proto.ToolsProto.ClientReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.st.cloud.gametool.proto.ToolsProto.ClientReq.class, com.st.cloud.gametool.proto.ToolsProto.ClientReq.Builder.class);
      }

      // Construct using com.st.cloud.gametool.proto.ToolsProto.ClientReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        score_ = 0L;
        bet_ = 0L;
        pay_ = false;
        rtp_ = "";
        useBloodPool_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientReq_descriptor;
      }

      @java.lang.Override
      public com.st.cloud.gametool.proto.ToolsProto.ClientReq getDefaultInstanceForType() {
        return com.st.cloud.gametool.proto.ToolsProto.ClientReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.st.cloud.gametool.proto.ToolsProto.ClientReq build() {
        com.st.cloud.gametool.proto.ToolsProto.ClientReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.st.cloud.gametool.proto.ToolsProto.ClientReq buildPartial() {
        com.st.cloud.gametool.proto.ToolsProto.ClientReq result = new com.st.cloud.gametool.proto.ToolsProto.ClientReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.st.cloud.gametool.proto.ToolsProto.ClientReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.score_ = score_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bet_ = bet_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.pay_ = pay_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.rtp_ = rtp_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.useBloodPool_ = useBloodPool_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.st.cloud.gametool.proto.ToolsProto.ClientReq) {
          return mergeFrom((com.st.cloud.gametool.proto.ToolsProto.ClientReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.st.cloud.gametool.proto.ToolsProto.ClientReq other) {
        if (other == com.st.cloud.gametool.proto.ToolsProto.ClientReq.getDefaultInstance()) return this;
        if (other.getScore() != 0L) {
          setScore(other.getScore());
        }
        if (other.getBet() != 0L) {
          setBet(other.getBet());
        }
        if (other.getPay() != false) {
          setPay(other.getPay());
        }
        if (!other.getRtp().isEmpty()) {
          rtp_ = other.rtp_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getUseBloodPool() != false) {
          setUseBloodPool(other.getUseBloodPool());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                score_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                bet_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                pay_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                rtp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 64: {
                useBloodPool_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long score_ ;
      /**
       * <pre>
       * 积分
       * </pre>
       *
       * <code>int64 score = 1;</code>
       * @return The score.
       */
      @java.lang.Override
      public long getScore() {
        return score_;
      }
      /**
       * <pre>
       * 积分
       * </pre>
       *
       * <code>int64 score = 1;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(long value) {

        score_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 积分
       * </pre>
       *
       * <code>int64 score = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0L;
        onChanged();
        return this;
      }

      private long bet_ ;
      /**
       * <pre>
       * 单注
       * </pre>
       *
       * <code>int64 bet = 2;</code>
       * @return The bet.
       */
      @java.lang.Override
      public long getBet() {
        return bet_;
      }
      /**
       * <pre>
       * 单注
       * </pre>
       *
       * <code>int64 bet = 2;</code>
       * @param value The bet to set.
       * @return This builder for chaining.
       */
      public Builder setBet(long value) {

        bet_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 单注
       * </pre>
       *
       * <code>int64 bet = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBet() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bet_ = 0L;
        onChanged();
        return this;
      }

      private boolean pay_ ;
      /**
       * <pre>
       * 是否购买模式
       * </pre>
       *
       * <code>bool pay = 3;</code>
       * @return The pay.
       */
      @java.lang.Override
      public boolean getPay() {
        return pay_;
      }
      /**
       * <pre>
       * 是否购买模式
       * </pre>
       *
       * <code>bool pay = 3;</code>
       * @param value The pay to set.
       * @return This builder for chaining.
       */
      public Builder setPay(boolean value) {

        pay_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否购买模式
       * </pre>
       *
       * <code>bool pay = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pay_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object rtp_ = "";
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 4;</code>
       * @return The rtp.
       */
      public java.lang.String getRtp() {
        java.lang.Object ref = rtp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rtp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 4;</code>
       * @return The bytes for rtp.
       */
      public com.google.protobuf.ByteString
          getRtpBytes() {
        java.lang.Object ref = rtp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rtp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 4;</code>
       * @param value The rtp to set.
       * @return This builder for chaining.
       */
      public Builder setRtp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rtp_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtp() {
        rtp_ = getDefaultInstance().getRtp();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 4;</code>
       * @param value The bytes for rtp to set.
       * @return This builder for chaining.
       */
      public Builder setRtpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rtp_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private boolean useBloodPool_ ;
      /**
       * <pre>
       * 使用血池
       * </pre>
       *
       * <code>bool useBloodPool = 8;</code>
       * @return The useBloodPool.
       */
      @java.lang.Override
      public boolean getUseBloodPool() {
        return useBloodPool_;
      }
      /**
       * <pre>
       * 使用血池
       * </pre>
       *
       * <code>bool useBloodPool = 8;</code>
       * @param value The useBloodPool to set.
       * @return This builder for chaining.
       */
      public Builder setUseBloodPool(boolean value) {

        useBloodPool_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 使用血池
       * </pre>
       *
       * <code>bool useBloodPool = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUseBloodPool() {
        bitField0_ = (bitField0_ & ~0x00000010);
        useBloodPool_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientReq)
    }

    // @@protoc_insertion_point(class_scope:ClientReq)
    private static final com.st.cloud.gametool.proto.ToolsProto.ClientReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.st.cloud.gametool.proto.ToolsProto.ClientReq();
    }

    public static com.st.cloud.gametool.proto.ToolsProto.ClientReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientReq>
        PARSER = new com.google.protobuf.AbstractParser<ClientReq>() {
      @java.lang.Override
      public ClientReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClientReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.st.cloud.gametool.proto.ToolsProto.ClientReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 赢金额
     * </pre>
     *
     * <code>int64 win = 1;</code>
     * @return The win.
     */
    long getWin();

    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 2;</code>
     * @return The rtp.
     */
    java.lang.String getRtp();
    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 2;</code>
     * @return The bytes for rtp.
     */
    com.google.protobuf.ByteString
        getRtpBytes();

    /**
     * <pre>
     * 是否免费
     * </pre>
     *
     * <code>bool free = 3;</code>
     * @return The free.
     */
    boolean getFree();

    /**
     * <pre>
     * 中奖次数
     * </pre>
     *
     * <code>int32 winNum = 4;</code>
     * @return The winNum.
     */
    int getWinNum();

    /**
     * <pre>
     * 中奖倍数
     * </pre>
     *
     * <code>int32 winMul = 5;</code>
     * @return The winMul.
     */
    int getWinMul();

    /**
     * <pre>
     * 中奖信息
     * </pre>
     *
     * <code>string winInfo = 6;</code>
     * @return The winInfo.
     */
    java.lang.String getWinInfo();
    /**
     * <pre>
     * 中奖信息
     * </pre>
     *
     * <code>string winInfo = 6;</code>
     * @return The bytes for winInfo.
     */
    com.google.protobuf.ByteString
        getWinInfoBytes();

    /**
     * <pre>
     * 游戏信息
     * </pre>
     *
     * <code>string gameInfo = 7;</code>
     * @return The gameInfo.
     */
    java.lang.String getGameInfo();
    /**
     * <pre>
     * 游戏信息
     * </pre>
     *
     * <code>string gameInfo = 7;</code>
     * @return The bytes for gameInfo.
     */
    com.google.protobuf.ByteString
        getGameInfoBytes();
  }
  /**
   * Protobuf type {@code ClientRes}
   */
  public static final class ClientRes extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientRes)
      ClientResOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        ClientRes.class.getName());
    }
    // Use ClientRes.newBuilder() to construct.
    private ClientRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClientRes() {
      rtp_ = "";
      winInfo_ = "";
      gameInfo_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.st.cloud.gametool.proto.ToolsProto.ClientRes.class, com.st.cloud.gametool.proto.ToolsProto.ClientRes.Builder.class);
    }

    public static final int WIN_FIELD_NUMBER = 1;
    private long win_ = 0L;
    /**
     * <pre>
     * 赢金额
     * </pre>
     *
     * <code>int64 win = 1;</code>
     * @return The win.
     */
    @java.lang.Override
    public long getWin() {
      return win_;
    }

    public static final int RTP_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rtp_ = "";
    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 2;</code>
     * @return The rtp.
     */
    @java.lang.Override
    public java.lang.String getRtp() {
      java.lang.Object ref = rtp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 作弊值
     * </pre>
     *
     * <code>string rtp = 2;</code>
     * @return The bytes for rtp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRtpBytes() {
      java.lang.Object ref = rtp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FREE_FIELD_NUMBER = 3;
    private boolean free_ = false;
    /**
     * <pre>
     * 是否免费
     * </pre>
     *
     * <code>bool free = 3;</code>
     * @return The free.
     */
    @java.lang.Override
    public boolean getFree() {
      return free_;
    }

    public static final int WINNUM_FIELD_NUMBER = 4;
    private int winNum_ = 0;
    /**
     * <pre>
     * 中奖次数
     * </pre>
     *
     * <code>int32 winNum = 4;</code>
     * @return The winNum.
     */
    @java.lang.Override
    public int getWinNum() {
      return winNum_;
    }

    public static final int WINMUL_FIELD_NUMBER = 5;
    private int winMul_ = 0;
    /**
     * <pre>
     * 中奖倍数
     * </pre>
     *
     * <code>int32 winMul = 5;</code>
     * @return The winMul.
     */
    @java.lang.Override
    public int getWinMul() {
      return winMul_;
    }

    public static final int WININFO_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object winInfo_ = "";
    /**
     * <pre>
     * 中奖信息
     * </pre>
     *
     * <code>string winInfo = 6;</code>
     * @return The winInfo.
     */
    @java.lang.Override
    public java.lang.String getWinInfo() {
      java.lang.Object ref = winInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        winInfo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 中奖信息
     * </pre>
     *
     * <code>string winInfo = 6;</code>
     * @return The bytes for winInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWinInfoBytes() {
      java.lang.Object ref = winInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        winInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GAMEINFO_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object gameInfo_ = "";
    /**
     * <pre>
     * 游戏信息
     * </pre>
     *
     * <code>string gameInfo = 7;</code>
     * @return The gameInfo.
     */
    @java.lang.Override
    public java.lang.String getGameInfo() {
      java.lang.Object ref = gameInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameInfo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 游戏信息
     * </pre>
     *
     * <code>string gameInfo = 7;</code>
     * @return The bytes for gameInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGameInfoBytes() {
      java.lang.Object ref = gameInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (win_ != 0L) {
        output.writeInt64(1, win_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rtp_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, rtp_);
      }
      if (free_ != false) {
        output.writeBool(3, free_);
      }
      if (winNum_ != 0) {
        output.writeInt32(4, winNum_);
      }
      if (winMul_ != 0) {
        output.writeInt32(5, winMul_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(winInfo_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, winInfo_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameInfo_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, gameInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (win_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, win_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rtp_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, rtp_);
      }
      if (free_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, free_);
      }
      if (winNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, winNum_);
      }
      if (winMul_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, winMul_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(winInfo_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, winInfo_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gameInfo_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, gameInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.st.cloud.gametool.proto.ToolsProto.ClientRes)) {
        return super.equals(obj);
      }
      com.st.cloud.gametool.proto.ToolsProto.ClientRes other = (com.st.cloud.gametool.proto.ToolsProto.ClientRes) obj;

      if (getWin()
          != other.getWin()) return false;
      if (!getRtp()
          .equals(other.getRtp())) return false;
      if (getFree()
          != other.getFree()) return false;
      if (getWinNum()
          != other.getWinNum()) return false;
      if (getWinMul()
          != other.getWinMul()) return false;
      if (!getWinInfo()
          .equals(other.getWinInfo())) return false;
      if (!getGameInfo()
          .equals(other.getGameInfo())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWin());
      hash = (37 * hash) + RTP_FIELD_NUMBER;
      hash = (53 * hash) + getRtp().hashCode();
      hash = (37 * hash) + FREE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFree());
      hash = (37 * hash) + WINNUM_FIELD_NUMBER;
      hash = (53 * hash) + getWinNum();
      hash = (37 * hash) + WINMUL_FIELD_NUMBER;
      hash = (53 * hash) + getWinMul();
      hash = (37 * hash) + WININFO_FIELD_NUMBER;
      hash = (53 * hash) + getWinInfo().hashCode();
      hash = (37 * hash) + GAMEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getGameInfo().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.st.cloud.gametool.proto.ToolsProto.ClientRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientRes)
        com.st.cloud.gametool.proto.ToolsProto.ClientResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.st.cloud.gametool.proto.ToolsProto.ClientRes.class, com.st.cloud.gametool.proto.ToolsProto.ClientRes.Builder.class);
      }

      // Construct using com.st.cloud.gametool.proto.ToolsProto.ClientRes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        win_ = 0L;
        rtp_ = "";
        free_ = false;
        winNum_ = 0;
        winMul_ = 0;
        winInfo_ = "";
        gameInfo_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.st.cloud.gametool.proto.ToolsProto.internal_static_ClientRes_descriptor;
      }

      @java.lang.Override
      public com.st.cloud.gametool.proto.ToolsProto.ClientRes getDefaultInstanceForType() {
        return com.st.cloud.gametool.proto.ToolsProto.ClientRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.st.cloud.gametool.proto.ToolsProto.ClientRes build() {
        com.st.cloud.gametool.proto.ToolsProto.ClientRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.st.cloud.gametool.proto.ToolsProto.ClientRes buildPartial() {
        com.st.cloud.gametool.proto.ToolsProto.ClientRes result = new com.st.cloud.gametool.proto.ToolsProto.ClientRes(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.st.cloud.gametool.proto.ToolsProto.ClientRes result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.win_ = win_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rtp_ = rtp_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.free_ = free_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.winNum_ = winNum_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.winMul_ = winMul_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.winInfo_ = winInfo_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.gameInfo_ = gameInfo_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.st.cloud.gametool.proto.ToolsProto.ClientRes) {
          return mergeFrom((com.st.cloud.gametool.proto.ToolsProto.ClientRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.st.cloud.gametool.proto.ToolsProto.ClientRes other) {
        if (other == com.st.cloud.gametool.proto.ToolsProto.ClientRes.getDefaultInstance()) return this;
        if (other.getWin() != 0L) {
          setWin(other.getWin());
        }
        if (!other.getRtp().isEmpty()) {
          rtp_ = other.rtp_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getFree() != false) {
          setFree(other.getFree());
        }
        if (other.getWinNum() != 0) {
          setWinNum(other.getWinNum());
        }
        if (other.getWinMul() != 0) {
          setWinMul(other.getWinMul());
        }
        if (!other.getWinInfo().isEmpty()) {
          winInfo_ = other.winInfo_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getGameInfo().isEmpty()) {
          gameInfo_ = other.gameInfo_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                win_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                rtp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                free_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                winNum_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                winMul_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                winInfo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                gameInfo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long win_ ;
      /**
       * <pre>
       * 赢金额
       * </pre>
       *
       * <code>int64 win = 1;</code>
       * @return The win.
       */
      @java.lang.Override
      public long getWin() {
        return win_;
      }
      /**
       * <pre>
       * 赢金额
       * </pre>
       *
       * <code>int64 win = 1;</code>
       * @param value The win to set.
       * @return This builder for chaining.
       */
      public Builder setWin(long value) {

        win_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 赢金额
       * </pre>
       *
       * <code>int64 win = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        win_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object rtp_ = "";
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @return The rtp.
       */
      public java.lang.String getRtp() {
        java.lang.Object ref = rtp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rtp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @return The bytes for rtp.
       */
      public com.google.protobuf.ByteString
          getRtpBytes() {
        java.lang.Object ref = rtp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rtp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @param value The rtp to set.
       * @return This builder for chaining.
       */
      public Builder setRtp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rtp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtp() {
        rtp_ = getDefaultInstance().getRtp();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 作弊值
       * </pre>
       *
       * <code>string rtp = 2;</code>
       * @param value The bytes for rtp to set.
       * @return This builder for chaining.
       */
      public Builder setRtpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rtp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean free_ ;
      /**
       * <pre>
       * 是否免费
       * </pre>
       *
       * <code>bool free = 3;</code>
       * @return The free.
       */
      @java.lang.Override
      public boolean getFree() {
        return free_;
      }
      /**
       * <pre>
       * 是否免费
       * </pre>
       *
       * <code>bool free = 3;</code>
       * @param value The free to set.
       * @return This builder for chaining.
       */
      public Builder setFree(boolean value) {

        free_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否免费
       * </pre>
       *
       * <code>bool free = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFree() {
        bitField0_ = (bitField0_ & ~0x00000004);
        free_ = false;
        onChanged();
        return this;
      }

      private int winNum_ ;
      /**
       * <pre>
       * 中奖次数
       * </pre>
       *
       * <code>int32 winNum = 4;</code>
       * @return The winNum.
       */
      @java.lang.Override
      public int getWinNum() {
        return winNum_;
      }
      /**
       * <pre>
       * 中奖次数
       * </pre>
       *
       * <code>int32 winNum = 4;</code>
       * @param value The winNum to set.
       * @return This builder for chaining.
       */
      public Builder setWinNum(int value) {

        winNum_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 中奖次数
       * </pre>
       *
       * <code>int32 winNum = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWinNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        winNum_ = 0;
        onChanged();
        return this;
      }

      private int winMul_ ;
      /**
       * <pre>
       * 中奖倍数
       * </pre>
       *
       * <code>int32 winMul = 5;</code>
       * @return The winMul.
       */
      @java.lang.Override
      public int getWinMul() {
        return winMul_;
      }
      /**
       * <pre>
       * 中奖倍数
       * </pre>
       *
       * <code>int32 winMul = 5;</code>
       * @param value The winMul to set.
       * @return This builder for chaining.
       */
      public Builder setWinMul(int value) {

        winMul_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 中奖倍数
       * </pre>
       *
       * <code>int32 winMul = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWinMul() {
        bitField0_ = (bitField0_ & ~0x00000010);
        winMul_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object winInfo_ = "";
      /**
       * <pre>
       * 中奖信息
       * </pre>
       *
       * <code>string winInfo = 6;</code>
       * @return The winInfo.
       */
      public java.lang.String getWinInfo() {
        java.lang.Object ref = winInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          winInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 中奖信息
       * </pre>
       *
       * <code>string winInfo = 6;</code>
       * @return The bytes for winInfo.
       */
      public com.google.protobuf.ByteString
          getWinInfoBytes() {
        java.lang.Object ref = winInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          winInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 中奖信息
       * </pre>
       *
       * <code>string winInfo = 6;</code>
       * @param value The winInfo to set.
       * @return This builder for chaining.
       */
      public Builder setWinInfo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        winInfo_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 中奖信息
       * </pre>
       *
       * <code>string winInfo = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearWinInfo() {
        winInfo_ = getDefaultInstance().getWinInfo();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 中奖信息
       * </pre>
       *
       * <code>string winInfo = 6;</code>
       * @param value The bytes for winInfo to set.
       * @return This builder for chaining.
       */
      public Builder setWinInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        winInfo_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object gameInfo_ = "";
      /**
       * <pre>
       * 游戏信息
       * </pre>
       *
       * <code>string gameInfo = 7;</code>
       * @return The gameInfo.
       */
      public java.lang.String getGameInfo() {
        java.lang.Object ref = gameInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gameInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 游戏信息
       * </pre>
       *
       * <code>string gameInfo = 7;</code>
       * @return The bytes for gameInfo.
       */
      public com.google.protobuf.ByteString
          getGameInfoBytes() {
        java.lang.Object ref = gameInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gameInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 游戏信息
       * </pre>
       *
       * <code>string gameInfo = 7;</code>
       * @param value The gameInfo to set.
       * @return This builder for chaining.
       */
      public Builder setGameInfo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        gameInfo_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 游戏信息
       * </pre>
       *
       * <code>string gameInfo = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGameInfo() {
        gameInfo_ = getDefaultInstance().getGameInfo();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 游戏信息
       * </pre>
       *
       * <code>string gameInfo = 7;</code>
       * @param value The bytes for gameInfo to set.
       * @return This builder for chaining.
       */
      public Builder setGameInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        gameInfo_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientRes)
    }

    // @@protoc_insertion_point(class_scope:ClientRes)
    private static final com.st.cloud.gametool.proto.ToolsProto.ClientRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.st.cloud.gametool.proto.ToolsProto.ClientRes();
    }

    public static com.st.cloud.gametool.proto.ToolsProto.ClientRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientRes>
        PARSER = new com.google.protobuf.AbstractParser<ClientRes>() {
      @java.lang.Override
      public ClientRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClientRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.st.cloud.gametool.proto.ToolsProto.ClientRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Tools.proto\"W\n\tClientReq\022\r\n\005score\030\001 \001(" +
      "\003\022\013\n\003bet\030\002 \001(\003\022\013\n\003pay\030\003 \001(\010\022\013\n\003rtp\030\004 \001(\t" +
      "\022\024\n\014useBloodPool\030\010 \001(\010\"v\n\tClientRes\022\013\n\003w" +
      "in\030\001 \001(\003\022\013\n\003rtp\030\002 \001(\t\022\014\n\004free\030\003 \001(\010\022\016\n\006w" +
      "inNum\030\004 \001(\005\022\016\n\006winMul\030\005 \001(\005\022\017\n\007winInfo\030\006" +
      " \001(\t\022\020\n\010gameInfo\030\007 \001(\tB)\n\033com.st.cloud.g" +
      "ametool.protoB\nToolsProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ClientReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientReq_descriptor,
        new java.lang.String[] { "Score", "Bet", "Pay", "Rtp", "UseBloodPool", });
    internal_static_ClientRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientRes_descriptor,
        new java.lang.String[] { "Win", "Rtp", "Free", "WinNum", "WinMul", "WinInfo", "GameInfo", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
